# Generated by Django 4.2.14 on 2024-07-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_customuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user',
        ),
    ]
